import { useCallback } from "react";
import { useLanguageStore } from "../../store/LanguageStore";
import lg from "./content/lg.json";
import rny from "./content/rny.json";

// Prayer content (mysteries, stations, novena texts, Supabase prayers) is
// translated paragraph by paragraph into these dictionaries, keyed by the
// English paragraph. Generated by scripts/translate.mjs.
const DICTIONARIES: Record<string, Record<string, string>> = { lg, rny };

// Must match the split in scripts/translate.mjs
export const splitParagraphs = (text: string) =>
  text.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);

export function translateContent(text: string | undefined | null, language: string): string {
  if (!text) return text ?? "";
  const dictionary = DICTIONARIES[language];
  if (!dictionary) return text;
  return splitParagraphs(text)
    .map((paragraph) => dictionary[paragraph] ?? paragraph)
    .join("\n\n");
}

// True when every paragraph of `text` has a translation in `language`
export function hasContentTranslation(text: string | undefined | null, language: string) {
  const dictionary = DICTIONARIES[language];
  if (!text || !dictionary) return false;
  return splitParagraphs(text).every((paragraph) => paragraph in dictionary);
}

// `tc(english)` returns the text in the chosen language, or English if it has
// no translation yet
export function useContent() {
  const { language } = useLanguageStore();
  return useCallback((text: string | undefined | null) => translateContent(text, language), [language]);
}
